#!/usr/bin/env php
<?php
/**
 * Install CKeditor archive into Dynacase context dir
 *
 * @author Anakeen 2012
 */

$WIFF_ROOT = getenv("WIFF_ROOT");
if( $WIFF_ROOT === false ) {
  print "WIFF_ROOT environment variable is not set!\n";
  exit(1);
}

$WIFF_CONTEXT_ROOT = getenv("WIFF_CONTEXT_ROOT");
if( $WIFF_CONTEXT_ROOT === false ) {
  print "WIFF_CONTEXT_ROOT environment variable not set!\n";
  exit(1);
}

set_include_path(get_include_path().PATH_SEPARATOR.$WIFF_CONTEXT_ROOT.PATH_SEPARATOR."$WIFF_ROOT/include");



include_once('WHAT/Lib.System.php');

$ck_zip = $argv[1];
if( $ck_zip === NULL ) {
  print sprintf("Missing CKeditor archive argument\n");
  exit(1);
}
$ck_zip = realpath($ck_zip);
if( ! is_file($ck_zip) ) {
  print sprintf("CKeditor archive not found at '%s'\n", $ck_zip);
  exit(1);
}

$ret = chdir(sprintf("%s", $WIFF_CONTEXT_ROOT));
if( $ret === false ) {
  print sprintf("Could not change directory to '%s'\n", $WIFF_CONTEXT_ROOT);
  exit(1);
}

$tmpfile = LibSystem::tempnam(null, 'ckeditor_untar');
if( $tmpfile === false ) {
  print sprintf("Could not create temporary file\n");
  exit(1);
}

$tempdir = basename($tmpfile);
$ret = mkdir($tempdir);
if( $ret === false ) {
  print sprintf("Could not create temporary directory '%s'\n", $tempdir);
  @unlink($tmpfile);
  exit(1);
}

// Unpack archive in tempdir
$cmd = sprintf('unzip -d "%s" "%s" > "%s" 2>&1', escapeshellcmd($tempdir), escapeshellcmd($ck_zip), escapeshellcmd($tmpfile));
system($cmd, $ret);

$output = file_get_contents($tmpfile);
@unlink($tmpfile);

if( $ret !== 0 ) {
  print sprintf('Error unzip"%s" -zcf "%s"\n', $tempdir, escapeshellcmd($ck_zip));
  exit(1);
}

// Set directory/files rights
$cmd = sprintf('find "%s" -type d -exec chmod 0755 {} \; > /dev/null 2>&1', escapeshellcmd($tempdir));
system($cmd, $ret);
if( $ret !== 0 ) {
    print sprintf('Error setting rights on directories\n');
    exit(1);
}
$cmd = sprintf('find "%s" -type f -exec chmod 0644 {} \; > /dev/null 2>&1', escapeshellcmd($tempdir));
system($cmd, $ret);
if( $ret !== 0 ) {
    print sprintf('Error setting rights on files\n');
    exit(1);
}

// Search for a /ckeditor/ subdir in the unpacked archive
$fh = opendir($tempdir);
if( $fh === false ) {
  print sprintf("Error opening temporary directory '%s'\n", $tempdir);
  exit(1);
}

$fck_subdir = false;
while( ($file = readdir($fh)) !== false ) {
  if( is_dir(sprintf("%s/%s", $tempdir, $file)) && preg_match("/^ckeditor$/", $file) ) {
    $fck_subdir = $file;
    break;
  }
}
if( $fck_subdir === false ) {
  print sprintf("Could not find a valid ckeditor subdir in '%s'\n", $tempdir);
  exit(1);
}

// Create ckeditor dir if it does not exists
if( ! is_dir('lib/ckeditor') ) {
  $ret = mkdir('lib/ckeditor');
  if( $ret === false ) {
    print sprintf("Could not create 'lib/ckeditor' directory\n");
    exit(1);
  }
}
if( ! is_dir('lib/ckeditor/4') ) {
  $ret = mkdir('lib/ckeditor/4');
  if( $ret === false ) {
    print sprintf("Could not create 'lib/ckeditor/4' directory\n");
    exit(1);
  }
}

// Copy new ckeditor files over existing ckeditor directory
$cmd = sprintf('tar -C "%s/%s" -cf - . | tar -C "%s" -xf -', escapeshellcmd($tempdir), escapeshellcmd($fck_subdir), "lib/ckeditor/4");
system($cmd, $ret);

if( $ret !== 0 ) {
  print sprintf('Error copying ck files (%s)\n', $cmd);
  exit(1);
}

// Cleanup tempdir
$cmd = sprintf('rm -Rf "%s"', escapeshellcmd($tempdir));
system($cmd, $ret);

exit(0);

?>
